package panelView;

import control.*;
import Exception.InputKosongException;

import java.util.List;
import javax.swing.JOptionPane;
import java.awt.Component;
import javax.swing.table.TableModel;

import model.*;

public class TransaksiMainPanel extends javax.swing.JPanel {

    private PembelianKendaraanControl pembelianControl;
    private CustomerControlE customerControl;
    private KendaraanControlE kendaraanControl;

    private PembelianKendaraan pk = null;
    String action = null;
    int selectedId = 0;

    List<CustomerE> listCustomer;
    List<KendaraanE> listKendaraan;

    private Component rootPane;

    //Dropdwn Kendaraan
    public void setKendaraanToDropdown() {
        listKendaraan = kendaraanControl.showlistKendaraan();
        System.out.println(listKendaraan.size());

        for (KendaraanE k : listKendaraan) {
            namaKendaraanDropdown.addItem(k.toString());
        }
    }

    //Dropdown Customer
    public void setCustomerToDropdown() {
        listCustomer = customerControl.showListCustomer();
        for (CustomerE c : listCustomer) {
            namaCustomerDropdown.addItem(c.toString());
        }
    }

    //Radio Btn
    public void setRadioButtonValue() {
        bcaRadio.setActionCommand("BCA");
        briRadio.setActionCommand("BRI");
        mayRadio.setActionCommand("May Bank");
        bpdRadio.setActionCommand("BPD DIY");
        tunaiRadio.setActionCommand("Tunai");
    }

    //Show Table
    public void showTableBySearch(String target) {
        tablePembelian.setModel(pembelianControl.showTable(target));
    }

    //Exception
    public void inputKosongPembelianException() throws InputKosongException {
        if (namaCustomerDropdown.getSelectedIndex() == -1 || namaKendaraanDropdown.getSelectedIndex() == -1
                || jumlahPembelianInput.getText().isEmpty()
                || (!kursiCheckbox.isSelected() && !sistemNavigasiCheckbox.isSelected())
                || metodePembayaranGroup.getSelection().getActionCommand() == null) {
            throw new InputKosongException();
        }
    }

    // RESET
    public void clearText() {
        namaCustomerDropdown.setSelectedIndex(-1);
        namaKendaraanDropdown.setSelectedIndex(-1);

        kursiCheckbox.setSelected(false);
        sistemNavigasiCheckbox.setSelected(false);

        metodePembayaranGroup.clearSelection();

        searchTransaksiInputTextField.setText("");
        jumlahPembelianInput.setText("");
    }

    public void setEditDeleteBtn(boolean value) {
        barukanTransaksiButton.setEnabled(value);
        hapusTransaksiButton.setEnabled(value);
    }

    public void setComponent(boolean value) {
        namaCustomerDropdown.setEnabled(value);
        namaKendaraanDropdown.setEnabled(value);
        jumlahPembelianInput.setEnabled(value);

        kursiCheckbox.setEnabled(value);
        sistemNavigasiCheckbox.setEnabled(value);

        simpanTransaksiButton.setEnabled(value);
        batalTransaksiButton.setEnabled(value);
    }

    public void setRadioComponent(boolean value) {
        bcaRadio.setEnabled(value);
        briRadio.setEnabled(value);
        mayRadio.setEnabled(value);
        bpdRadio.setEnabled(value);
        tunaiRadio.setEnabled(value);
    }

    public TransaksiMainPanel() {
        initComponents();
        setOpaque(false);

        pembelianControl = new PembelianKendaraanControl();
        customerControl = new CustomerControlE();
        kendaraanControl = new KendaraanControlE();

        setCustomerToDropdown();
        setKendaraanToDropdown();
        setRadioButtonValue();

        showTableBySearch("");

        clearText();
        setComponent(false);
        setRadioComponent(false);
        setEditDeleteBtn(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        metodePembayaranGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        searchTransaksiInputPanel = new javax.swing.JPanel();
        searchTransaksiInputLabel = new javax.swing.JLabel();
        searchTransaksiInputTextField = new javax.swing.JTextField();
        searchTransaksiInputButton = new javax.swing.JButton();
        transaksiFormPanel = new javax.swing.JPanel();
        transaksiButtonPanel = new javax.swing.JPanel();
        barukanTransaksiButton = new javax.swing.JButton();
        hapusTransaksiButton = new javax.swing.JButton();
        tambahTransaksiButton = new javax.swing.JButton();
        namaCustomerPanel = new javax.swing.JPanel();
        namaCustomerDropdown = new javax.swing.JComboBox<>();
        namaCustomerLabel = new javax.swing.JLabel();
        namaKendaraanPanel = new javax.swing.JPanel();
        namaKendaraanDropdown = new javax.swing.JComboBox<>();
        namaKendaraanLabel = new javax.swing.JLabel();
        jumlahPembelianPanel = new javax.swing.JPanel();
        jumlahPembelianLabel = new javax.swing.JLabel();
        jumlahPembelianInput = new javax.swing.JTextField();
        metodePembayaranPanel = new javax.swing.JPanel();
        metodePembayaranLabel = new javax.swing.JLabel();
        bcaRadio = new javax.swing.JRadioButton();
        briRadio = new javax.swing.JRadioButton();
        mayRadio = new javax.swing.JRadioButton();
        bpdRadio = new javax.swing.JRadioButton();
        tunaiRadio = new javax.swing.JRadioButton();
        checkBoxPanel = new javax.swing.JPanel();
        atributLabel = new javax.swing.JLabel();
        kursiCheckbox = new javax.swing.JCheckBox();
        sistemNavigasiCheckbox = new javax.swing.JCheckBox();
        simpanTransaksiButton = new javax.swing.JButton();
        batalTransaksiButton = new javax.swing.JButton();
        pembelianScrollPane = new javax.swing.JScrollPane();
        tablePembelian = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(700, 518));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(700, 32767));
        mainPanel.setPreferredSize(new java.awt.Dimension(700, 518));

        searchTransaksiInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchTransaksiInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchTransaksiInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchTransaksiInputLabel.setText("Pencarian Transaksi");

        searchTransaksiInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchTransaksiInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTransaksiInputTextFieldActionPerformed(evt);
            }
        });
        searchTransaksiInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTransaksiInputTextFieldKeyPressed(evt);
            }
        });

        searchTransaksiInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchTransaksiInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchTransaksiInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchTransaksiInputButton.setText("Cari");
        searchTransaksiInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTransaksiInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchTransaksiInputPanelLayout = new javax.swing.GroupLayout(searchTransaksiInputPanel);
        searchTransaksiInputPanel.setLayout(searchTransaksiInputPanelLayout);
        searchTransaksiInputPanelLayout.setHorizontalGroup(
            searchTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTransaksiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTransaksiInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchTransaksiInputPanelLayout.createSequentialGroup()
                        .addComponent(searchTransaksiInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchTransaksiInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchTransaksiInputPanelLayout.setVerticalGroup(
            searchTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTransaksiInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTransaksiInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchTransaksiInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchTransaksiInputTextField)
                    .addComponent(searchTransaksiInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        transaksiFormPanel.setBackground(java.awt.Color.white);
        transaksiFormPanel.setMaximumSize(new java.awt.Dimension(700, 700));
        transaksiFormPanel.setPreferredSize(new java.awt.Dimension(700, 642));

        transaksiButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanTransaksiButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanTransaksiButton.setText("Barukan");
        barukanTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanTransaksiButtonActionPerformed(evt);
            }
        });

        hapusTransaksiButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusTransaksiButton.setText("Hapus");
        hapusTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTransaksiButtonActionPerformed(evt);
            }
        });

        tambahTransaksiButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahTransaksiButton.setText("Tambah");
        tambahTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahTransaksiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transaksiButtonPanelLayout = new javax.swing.GroupLayout(transaksiButtonPanel);
        transaksiButtonPanel.setLayout(transaksiButtonPanelLayout);
        transaksiButtonPanelLayout.setHorizontalGroup(
            transaksiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahTransaksiButton)
                .addGap(18, 18, 18)
                .addComponent(barukanTransaksiButton)
                .addGap(18, 18, 18)
                .addComponent(hapusTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksiButtonPanelLayout.setVerticalGroup(
            transaksiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transaksiButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanTransaksiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahTransaksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusTransaksiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaCustomerPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaCustomerPanel.setForeground(new java.awt.Color(255, 255, 255));
        namaCustomerPanel.setToolTipText("");

        namaCustomerDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaCustomerDropdownActionPerformed(evt);
            }
        });

        namaCustomerLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaCustomerLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaCustomerLabel.setText("Nama Customer");

        javax.swing.GroupLayout namaCustomerPanelLayout = new javax.swing.GroupLayout(namaCustomerPanel);
        namaCustomerPanel.setLayout(namaCustomerPanelLayout);
        namaCustomerPanelLayout.setHorizontalGroup(
            namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaCustomerDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaCustomerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaCustomerPanelLayout.setVerticalGroup(
            namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaCustomerDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        namaKendaraanPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaKendaraanPanel.setForeground(new java.awt.Color(255, 255, 255));
        namaKendaraanPanel.setToolTipText("");

        namaKendaraanLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaKendaraanLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        namaKendaraanLabel.setText("Nama Kendaraan");

        javax.swing.GroupLayout namaKendaraanPanelLayout = new javax.swing.GroupLayout(namaKendaraanPanel);
        namaKendaraanPanel.setLayout(namaKendaraanPanelLayout);
        namaKendaraanPanelLayout.setHorizontalGroup(
            namaKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKendaraanDropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaKendaraanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        namaKendaraanPanelLayout.setVerticalGroup(
            namaKendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKendaraanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKendaraanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKendaraanDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jumlahPembelianPanel.setBackground(new java.awt.Color(255, 255, 255));
        jumlahPembelianPanel.setForeground(new java.awt.Color(255, 255, 255));
        jumlahPembelianPanel.setToolTipText("");

        jumlahPembelianLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahPembelianLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jumlahPembelianLabel.setText("Jumlah Pembelian");

        javax.swing.GroupLayout jumlahPembelianPanelLayout = new javax.swing.GroupLayout(jumlahPembelianPanel);
        jumlahPembelianPanel.setLayout(jumlahPembelianPanelLayout);
        jumlahPembelianPanelLayout.setHorizontalGroup(
            jumlahPembelianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jumlahPembelianPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jumlahPembelianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jumlahPembelianInput)
                    .addComponent(jumlahPembelianLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jumlahPembelianPanelLayout.setVerticalGroup(
            jumlahPembelianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahPembelianPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jumlahPembelianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahPembelianInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        metodePembayaranPanel.setBackground(new java.awt.Color(255, 255, 255));
        metodePembayaranPanel.setForeground(new java.awt.Color(255, 255, 255));

        metodePembayaranLabel.setForeground(java.awt.Color.black);
        metodePembayaranLabel.setText("Metode Pembayaran");

        metodePembayaranGroup.add(bcaRadio);
        bcaRadio.setForeground(java.awt.Color.black);
        bcaRadio.setText("BCA");
        bcaRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaRadioActionPerformed(evt);
            }
        });

        metodePembayaranGroup.add(briRadio);
        briRadio.setForeground(java.awt.Color.black);
        briRadio.setText("BRI");

        metodePembayaranGroup.add(mayRadio);
        mayRadio.setForeground(java.awt.Color.black);
        mayRadio.setText("May Bank");

        metodePembayaranGroup.add(bpdRadio);
        bpdRadio.setForeground(java.awt.Color.black);
        bpdRadio.setText("BPD DIV");
        bpdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpdRadioActionPerformed(evt);
            }
        });

        metodePembayaranGroup.add(tunaiRadio);
        tunaiRadio.setForeground(java.awt.Color.black);
        tunaiRadio.setText("Tunai");

        javax.swing.GroupLayout metodePembayaranPanelLayout = new javax.swing.GroupLayout(metodePembayaranPanel);
        metodePembayaranPanel.setLayout(metodePembayaranPanelLayout);
        metodePembayaranPanelLayout.setHorizontalGroup(
            metodePembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodePembayaranPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(metodePembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metodePembayaranLabel)
                    .addComponent(bcaRadio)
                    .addComponent(briRadio)
                    .addComponent(mayRadio)
                    .addComponent(bpdRadio)
                    .addComponent(tunaiRadio))
                .addGap(25, 40, Short.MAX_VALUE))
        );
        metodePembayaranPanelLayout.setVerticalGroup(
            metodePembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(metodePembayaranPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(metodePembayaranLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcaRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(briRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mayRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpdRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tunaiRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkBoxPanel.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPanel.setForeground(java.awt.Color.black);

        atributLabel.setForeground(java.awt.Color.black);
        atributLabel.setText("Atribut Tambahan Kendaraan");

        kursiCheckbox.setForeground(java.awt.Color.black);
        kursiCheckbox.setText("Kursi Kulit");

        sistemNavigasiCheckbox.setForeground(java.awt.Color.black);
        sistemNavigasiCheckbox.setText("Sistem Navigasi GPS");

        javax.swing.GroupLayout checkBoxPanelLayout = new javax.swing.GroupLayout(checkBoxPanel);
        checkBoxPanel.setLayout(checkBoxPanelLayout);
        checkBoxPanelLayout.setHorizontalGroup(
            checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atributLabel)
                    .addComponent(sistemNavigasiCheckbox)
                    .addComponent(kursiCheckbox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        checkBoxPanelLayout.setVerticalGroup(
            checkBoxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBoxPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(atributLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kursiCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sistemNavigasiCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanTransaksiButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanTransaksiButton.setText("Simpan");
        simpanTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTransaksiButtonActionPerformed(evt);
            }
        });

        batalTransaksiButton.setBackground(new java.awt.Color(237, 8, 0));
        batalTransaksiButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        batalTransaksiButton.setForeground(new java.awt.Color(255, 255, 255));
        batalTransaksiButton.setText("Batalkan");
        batalTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalTransaksiButtonActionPerformed(evt);
            }
        });

        tablePembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePembelianMouseClicked(evt);
            }
        });
        pembelianScrollPane.setViewportView(tablePembelian);

        javax.swing.GroupLayout transaksiFormPanelLayout = new javax.swing.GroupLayout(transaksiFormPanel);
        transaksiFormPanel.setLayout(transaksiFormPanelLayout);
        transaksiFormPanelLayout.setHorizontalGroup(
            transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pembelianScrollPane)
                    .addGroup(transaksiFormPanelLayout.createSequentialGroup()
                        .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transaksiButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(transaksiFormPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaKendaraanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(namaCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jumlahPembelianPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(metodePembayaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanTransaksiButton)
                        .addGap(20, 20, 20)
                        .addComponent(batalTransaksiButton)
                        .addContainerGap())))
        );
        transaksiFormPanelLayout.setVerticalGroup(
            transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiFormPanelLayout.createSequentialGroup()
                .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(transaksiFormPanelLayout.createSequentialGroup()
                        .addComponent(transaksiButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaKendaraanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jumlahPembelianPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(batalTransaksiButton)
                                .addComponent(simpanTransaksiButton))))
                    .addGroup(transaksiFormPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(transaksiFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(metodePembayaranPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBoxPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 41, Short.MAX_VALUE)
                .addComponent(pembelianScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchTransaksiInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addComponent(transaksiFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchTransaksiInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksiFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTransaksiInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTransaksiInputTextFieldKeyPressed

    }//GEN-LAST:event_searchTransaksiInputTextFieldKeyPressed

    private void searchTransaksiInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTransaksiInputButtonActionPerformed

        showTableBySearch(searchTransaksiInputTextField.getText());

        clearText();
        setComponent(false);
        setEditDeleteBtn(false);
        setRadioComponent(false);
        metodePembayaranGroup.clearSelection();
        
        tambahTransaksiButton.setEnabled(true);

    }//GEN-LAST:event_searchTransaksiInputButtonActionPerformed

    private void barukanTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanTransaksiButtonActionPerformed

        action = "baharui";
        setComponent(true);
        namaCustomerDropdown.setEnabled(false);
        setEditDeleteBtn(true);
        setRadioComponent(false);

    }//GEN-LAST:event_barukanTransaksiButtonActionPerformed

    private void hapusTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTransaksiButtonActionPerformed

        action = "hapus";
        if (JOptionPane.showConfirmDialog(rootPane, "Yakin ingin melakukan " + action + "?")
                == JOptionPane.CLOSED_OPTION) {
            return;
        }
        
        pembelianControl.deletePembelianKendaraan(selectedId);

        clearText();
        setComponent(false);
        setRadioComponent(false);
        metodePembayaranGroup.clearSelection();
        tambahTransaksiButton.setEnabled(true);

        showTableBySearch("");    }//GEN-LAST:event_hapusTransaksiButtonActionPerformed

    private void tambahTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahTransaksiButtonActionPerformed
        action = "tambah";
        setComponent(true);
        setRadioComponent(true);


    }//GEN-LAST:event_tambahTransaksiButtonActionPerformed

    private void batalTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalTransaksiButtonActionPerformed

        clearText();
        setEditDeleteBtn(false);
        setComponent(false);
        setRadioComponent(false);
        tambahTransaksiButton.setEnabled(true);

    }//GEN-LAST:event_batalTransaksiButtonActionPerformed

    private void searchTransaksiInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTransaksiInputTextFieldActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_searchTransaksiInputTextFieldActionPerformed

    private void bcaRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bcaRadioActionPerformed

    private void bpdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpdRadioActionPerformed

    private void simpanTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTransaksiButtonActionPerformed
        try {
            inputKosongPembelianException();

            String atribut = "";
            String metodePembayaran = "";

            int selectedIndexCustomer = namaCustomerDropdown.getSelectedIndex();
            CustomerE selectedCustomer = listCustomer.get(selectedIndexCustomer);

            int selectedIndexKendaraan = namaKendaraanDropdown.getSelectedIndex();
            KendaraanE selectedKendaraan = listKendaraan.get(selectedIndexKendaraan);

            double totalHarga = Integer.parseInt(jumlahPembelianInput.getText()) * selectedKendaraan.getHarga();
            if (kursiCheckbox.isSelected() && sistemNavigasiCheckbox.isSelected()) {
                atribut = "Paket Lengkap";
            } else if (kursiCheckbox.isSelected()) {
                atribut = "Tambahan kursi kulit";
            } else {
                atribut = "Tambahkan sistem navigasi";
            }

            metodePembayaran = metodePembayaranGroup.getSelection().getActionCommand();
            if (JOptionPane.showConfirmDialog(rootPane, "Total pembayaran yang perlu Anda bayarkan adalah : Rp. " + totalHarga) == JOptionPane.CLOSED_OPTION) {
                return;
            }

            PembelianKendaraan pk = new PembelianKendaraan(selectedCustomer.getId_customer(),
                    Integer.parseInt(jumlahPembelianInput.getText()), selectedKendaraan.getId_kendaraan(), atribut,
                    metodePembayaran, selectedCustomer, selectedKendaraan);
            if (action.equals("tambah")) {
                pembelianControl.insertDataPembelianKendaraan(pk);
            } else {
                pembelianControl.updatePembelianKendaraan(pk, selectedId);
            }
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(rootPane, e.message());

        }
        clearText();
        setComponent(false);
        setRadioComponent(false);
        metodePembayaranGroup.clearSelection();
        tambahTransaksiButton.setEnabled(true);
        showTableBySearch("");

    }//GEN-LAST:event_simpanTransaksiButtonActionPerformed

    private void namaCustomerDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaCustomerDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaCustomerDropdownActionPerformed

    private void tablePembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePembelianMouseClicked
        //SEMANGATT

        int indexCustomer = -1, indexKendaraan = -1;
        action = "baharui";

        tambahTransaksiButton.setEnabled(false);
        batalTransaksiButton.setEnabled(true);
        simpanTransaksiButton.setEnabled(true);
        setEditDeleteBtn(true);

        setComponent(false);
        setRadioComponent(false);
        metodePembayaranGroup.clearSelection();

        int clickedRow = tablePembelian.getSelectedRow();
        TableModel tableModel = tablePembelian.getModel();

        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        jumlahPembelianInput.setText(tableModel.getValueAt(clickedRow, 3).toString());

        String metodePembayaran = tableModel.getValueAt(clickedRow, 5).toString();
        String atribut = tableModel.getValueAt(clickedRow, 4).toString();

        switch (metodePembayaran) {
            case "BCA":
                bcaRadio.setSelected(true);
                break;
            case "BRI":
                briRadio.setSelected(true);
                break;
            case "May Bank":
                mayRadio.setSelected(true);
                break;
            case "BPD DIY":
                bpdRadio.setSelected(true);
                break;
            case "Tunai":
                tunaiRadio.setSelected(true);
                break;
        }

        kursiCheckbox.setSelected(false);
        sistemNavigasiCheckbox.setSelected(false);

        switch (atribut) {
            case "Paket Lengkap":
                kursiCheckbox.setSelected(true);
                sistemNavigasiCheckbox.setSelected(true);
                break;
            case "Tambahan Sistem navigasi":
                sistemNavigasiCheckbox.setSelected(true);
                break;
            case "Tambahan kursi kulit":
                kursiCheckbox.setSelected(true);
                break;
        }

        for (CustomerE customer : listCustomer) {
            if (customer.getId_customer() == Integer.parseInt(tableModel.getValueAt(clickedRow, 6).toString())) {
                indexCustomer = listCustomer.indexOf(customer);
            }
        }

        for (KendaraanE kendaraan : listKendaraan) {
            if (kendaraan.getId_kendaraan().equals(tableModel.getValueAt(clickedRow, 7).toString())) {
                indexKendaraan = listKendaraan.indexOf(kendaraan);
            }
        }

        namaCustomerDropdown.setSelectedIndex(indexCustomer);
        namaKendaraanDropdown.setSelectedIndex(indexKendaraan);
        batalTransaksiButton.setEnabled(true);

    }//GEN-LAST:event_tablePembelianMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atributLabel;
    private javax.swing.JButton barukanTransaksiButton;
    private javax.swing.JButton batalTransaksiButton;
    private javax.swing.JRadioButton bcaRadio;
    private javax.swing.JRadioButton bpdRadio;
    private javax.swing.JRadioButton briRadio;
    private javax.swing.JPanel checkBoxPanel;
    private javax.swing.JButton hapusTransaksiButton;
    private javax.swing.JTextField jumlahPembelianInput;
    private javax.swing.JLabel jumlahPembelianLabel;
    private javax.swing.JPanel jumlahPembelianPanel;
    private javax.swing.JCheckBox kursiCheckbox;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton mayRadio;
    private javax.swing.ButtonGroup metodePembayaranGroup;
    private javax.swing.JLabel metodePembayaranLabel;
    private javax.swing.JPanel metodePembayaranPanel;
    private javax.swing.JComboBox<String> namaCustomerDropdown;
    private javax.swing.JLabel namaCustomerLabel;
    private javax.swing.JPanel namaCustomerPanel;
    private javax.swing.JComboBox<String> namaKendaraanDropdown;
    private javax.swing.JLabel namaKendaraanLabel;
    private javax.swing.JPanel namaKendaraanPanel;
    private javax.swing.JScrollPane pembelianScrollPane;
    private javax.swing.JButton searchTransaksiInputButton;
    private javax.swing.JLabel searchTransaksiInputLabel;
    private javax.swing.JPanel searchTransaksiInputPanel;
    private javax.swing.JTextField searchTransaksiInputTextField;
    private javax.swing.JButton simpanTransaksiButton;
    private javax.swing.JCheckBox sistemNavigasiCheckbox;
    private javax.swing.JTable tablePembelian;
    private javax.swing.JButton tambahTransaksiButton;
    private javax.swing.JPanel transaksiButtonPanel;
    private javax.swing.JPanel transaksiFormPanel;
    private javax.swing.JRadioButton tunaiRadio;
    // End of variables declaration//GEN-END:variables
}
