/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JComponent;
import panelView.CustomerMainPanel;
import panelView.KasirMainPanel;
import panelView.KendaraanMainPanel;
import panelView.PaketServisMainPanel;
import panelView.TransaksiMainPanel;

/**
 *
 * @author farel
 */
public class MainViewForm extends javax.swing.JFrame {

//    private int selectedIndex = -1;

    public MainViewForm() {
        initComponents();
        recolorDefaultSwitchPanel(0);
    }

    private void setForm(JComponent com) {
        contentPanel.removeAll();
        contentPanel.add(com);
        contentPanel.repaint();
        contentPanel.revalidate();
    }

    private void recolorDefaultSwitchPanel(int i) {
        repaint();
        customerPanel.setBackground(new Color(0, 0, 0, 0));
        kendaraanPanel.setBackground(new Color(0, 0, 0, 0));
        transaksiPanel.setBackground(new Color(0, 0, 0, 0));
        kasirPanel.setBackground(new Color(0, 0, 0, 0));
        sukuCadangPanel.setBackground(new Color(0, 0, 0, 0));
        switch (i) {
            case 1:
                customerPanel.setBackground(new Color(241, 53, 21, 200));
                break;
            case 2:
                kendaraanPanel.setBackground(new Color(241, 53, 21, 200));
                break;
            case 3:
                kasirPanel.setBackground(new Color(241, 53, 21, 200));
                break;
            case 4:
                sukuCadangPanel.setBackground(new Color(241, 53, 21, 200));
                break;
            case 5:
                transaksiPanel.setBackground(new Color(241, 53, 21, 200));
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidePanel1 = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoIcon = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        customerPanel = new javax.swing.JPanel();
        customerLabel = new javax.swing.JLabel();
        kendaraanPanel = new javax.swing.JPanel();
        kendaraanLabel = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        transaksiLabel = new javax.swing.JLabel();
        kasirPanel = new javax.swing.JPanel();
        kasirLabel = new javax.swing.JLabel();
        sukuCadangPanel = new javax.swing.JPanel();
        sukuCadang = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sidePanel1.setBackground(new java.awt.Color(27, 26, 85));

        logoPanel.setBackground(new java.awt.Color(27, 26, 85));

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/gearIcon_48x48.png"))); // NOI18N

        logoLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 22)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("ATMA AUTO");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoLabel)
                .addGap(26, 26, 26))
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(logoIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLabel)
                .addGap(27, 27, 27))
        );

        customerPanel.setBackground(new java.awt.Color(27, 26, 85));
        customerPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        customerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                customerPanelMousePressed(evt);
            }
        });

        customerLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        customerLabel.setForeground(java.awt.Color.white);
        customerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/customerIcon_48x48.png"))); // NOI18N
        customerLabel.setText("Customer");
        customerLabel.setIconTextGap(15);

        javax.swing.GroupLayout customerPanelLayout = new javax.swing.GroupLayout(customerPanel);
        customerPanel.setLayout(customerPanelLayout);
        customerPanelLayout.setHorizontalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(customerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerPanelLayout.setVerticalGroup(
            customerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(customerLabel)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        kendaraanPanel.setBackground(new java.awt.Color(27, 26, 85));
        kendaraanPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        kendaraanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kendaraanPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kendaraanPanelMousePressed(evt);
            }
        });

        kendaraanLabel.setBackground(new java.awt.Color(255, 255, 255));
        kendaraanLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kendaraanLabel.setForeground(new java.awt.Color(255, 255, 255));
        kendaraanLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vehicleIcon_48x48.png"))); // NOI18N
        kendaraanLabel.setText("Kendaraan");
        kendaraanLabel.setIconTextGap(15);

        javax.swing.GroupLayout kendaraanPanelLayout = new javax.swing.GroupLayout(kendaraanPanel);
        kendaraanPanel.setLayout(kendaraanPanelLayout);
        kendaraanPanelLayout.setHorizontalGroup(
            kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(kendaraanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kendaraanPanelLayout.setVerticalGroup(
            kendaraanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(kendaraanLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        transaksiPanel.setBackground(new java.awt.Color(27, 26, 85));
        transaksiPanel.setForeground(new java.awt.Color(255, 255, 255));
        transaksiPanel.setToolTipText("");
        transaksiPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        transaksiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transaksiPanelMousePressed(evt);
            }
        });

        transaksiLabel.setBackground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        transaksiLabel.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transactionIcon_48x48.png"))); // NOI18N
        transaksiLabel.setText("Transaksi");

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(transaksiLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(transaksiLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        kasirPanel.setBackground(new java.awt.Color(27, 26, 85));
        kasirPanel.setForeground(new java.awt.Color(255, 255, 255));
        kasirPanel.setToolTipText("");
        kasirPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        kasirPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kasirPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kasirPanelMousePressed(evt);
            }
        });

        kasirLabel.setBackground(new java.awt.Color(255, 255, 255));
        kasirLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kasirLabel.setForeground(new java.awt.Color(255, 255, 255));
        kasirLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cashiericon_48x48.png"))); // NOI18N
        kasirLabel.setText("Kasir");
        kasirLabel.setToolTipText("");
        kasirLabel.setIconTextGap(15);

        javax.swing.GroupLayout kasirPanelLayout = new javax.swing.GroupLayout(kasirPanel);
        kasirPanel.setLayout(kasirPanelLayout);
        kasirPanelLayout.setHorizontalGroup(
            kasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(kasirLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kasirPanelLayout.setVerticalGroup(
            kasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(kasirLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sukuCadangPanel.setBackground(new java.awt.Color(27, 26, 85));
        sukuCadangPanel.setForeground(new java.awt.Color(255, 255, 255));
        sukuCadangPanel.setToolTipText("");
        sukuCadangPanel.setPreferredSize(new java.awt.Dimension(140, 70));
        sukuCadangPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sukuCadangPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sukuCadangPanelMousePressed(evt);
            }
        });

        sukuCadang.setBackground(new java.awt.Color(255, 255, 255));
        sukuCadang.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        sukuCadang.setForeground(new java.awt.Color(255, 255, 255));
        sukuCadang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/wrenchicon_48x48.png"))); // NOI18N
        sukuCadang.setText("Paket Servis");
        sukuCadang.setIconTextGap(15);

        javax.swing.GroupLayout sukuCadangPanelLayout = new javax.swing.GroupLayout(sukuCadangPanel);
        sukuCadangPanel.setLayout(sukuCadangPanelLayout);
        sukuCadangPanelLayout.setHorizontalGroup(
            sukuCadangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sukuCadangPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(sukuCadang)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        sukuCadangPanelLayout.setVerticalGroup(
            sukuCadangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sukuCadangPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(sukuCadang)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanel1Layout = new javax.swing.GroupLayout(sidePanel1);
        sidePanel1.setLayout(sidePanel1Layout);
        sidePanel1Layout.setHorizontalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(kendaraanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(customerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(kasirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(sukuCadangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addGroup(sidePanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidePanel1Layout.setVerticalGroup(
            sidePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kendaraanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kasirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sukuCadangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sukuCadangPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sukuCadangPanelMousePressed
        // TODO add your handling code here:
        setPanel(4);
    }//GEN-LAST:event_sukuCadangPanelMousePressed

    private void sukuCadangPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sukuCadangPanelMouseClicked
        //        setPanel(4);
    }//GEN-LAST:event_sukuCadangPanelMouseClicked

    private void kasirPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirPanelMousePressed
        // TODO add your handling code here:
        setPanel(3);
    }//GEN-LAST:event_kasirPanelMousePressed

    private void kasirPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kasirPanelMouseClicked
        //        // TODO add your handling code here:
        //        setPanel(3);
    }//GEN-LAST:event_kasirPanelMouseClicked

    private void transaksiPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiPanelMousePressed
        // TODO add your handling code here:
        setPanel(5);
    }//GEN-LAST:event_transaksiPanelMousePressed

    private void transaksiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiPanelMouseClicked
        // TODO add your handling code here:
        //        setPanel(5);
    }//GEN-LAST:event_transaksiPanelMouseClicked

    private void kendaraanPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraanPanelMousePressed
        // TODO add your handling code here:
        setPanel(2);
    }//GEN-LAST:event_kendaraanPanelMousePressed

    private void kendaraanPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kendaraanPanelMouseClicked

        //        setPanel(2);
    }//GEN-LAST:event_kendaraanPanelMouseClicked

    private void customerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerPanelMousePressed

        // TODO add your handling code here:
        setPanel(1);
    }//GEN-LAST:event_customerPanelMousePressed

    private void customerPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerPanelMouseClicked
        //        setPanel(1);
    }//GEN-LAST:event_customerPanelMouseClicked

    private void setPanel(int selected) {
        recolorDefaultSwitchPanel(selected);
        switch (selected) {
            case 1:
                setForm(new CustomerMainPanel());
                break;
            case 2:
                setForm(new KendaraanMainPanel());
                break;
            case 3:
                setForm(new KasirMainPanel());
                break;
            case 4:
                setForm(new PaketServisMainPanel());
                break;
            case 5:
                setForm(new TransaksiMainPanel());
                break;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JLabel kasirLabel;
    private javax.swing.JPanel kasirPanel;
    private javax.swing.JLabel kendaraanLabel;
    private javax.swing.JPanel kendaraanPanel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidePanel1;
    private javax.swing.JLabel sukuCadang;
    private javax.swing.JPanel sukuCadangPanel;
    private javax.swing.JLabel transaksiLabel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
