package panelView;

import Exception.InputKosongException;
import Exception.NoTelponException;
import control.KasirControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import model.Kasir;

public class KasirMainPanel extends javax.swing.JPanel {

    private KasirControl kk = new KasirControl();
    private Kasir k = null;
    String actionKasir = null;
    int idKasir = 0;
    private Component rootPane;

    private void inputKosongKasirException() throws InputKosongException {
        if (namaKasirInputTextField.getText().isEmpty() || shiftInputTextArea.getText().isEmpty() || nomorLoketInputTextField.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }

    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private void noTelponException() throws NoTelponException {
        if (!nomorLoketInputTextField.getText().matches("^\\+?[0-9]+$")) {
            throw new NoTelponException();
        }
    }

    public KasirMainPanel() {
        initComponents();
        setOpaque(false);
        showKasir();
        setComponentsKasir(false);
        setEditDeleteButtonKasir(false);
        clearTextKasir();
    }

    // Kasir Set Komponen
    public void setComponentsKasir(boolean value) {
        namaKasirInputTextField.setEnabled(value);
        nomorLoketInputTextField.setEnabled(value);
        shiftInputTextArea.setEnabled(value);
    }

    // Kasir Set Edit Delete Button
    public void setEditDeleteButtonKasir(boolean value) {
        barukanKasirButton.setEnabled(value);
        hapusKasirButton.setEnabled(value);
    }

    // Kasir Clear Text
    public void clearTextKasir() {
        namaKasirInputTextField.setText("");
        nomorLoketInputTextField.setText("");
        shiftInputTextArea.setText("");
        searchKasirInputTextField.setText("");
    }

    public void showKasir() {
        kasirTextArea.setText("List Kasir: \n ============= \n" + kk.showAllStringKasir());
    }

    private void doSearchKasir() {
        if (searchKasirInputTextField.getText().isEmpty()) {
            return;
        }
        Kasir k = kk.searchKasirById(Integer.parseInt(searchKasirInputTextField.getText()));
        if (k == null) {
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
            return;
        }
        setEditDeleteButtonKasir(true);
        clearTextKasir();

        namaKasirInputTextField.setText(k.getNama_kasir());
        nomorLoketInputTextField.setText(Integer.toString(k.getNomor_loket()));
        shiftInputTextArea.setText(k.getShift());
        idKasir = k.getId_kasir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchKasirInputPanel = new javax.swing.JPanel();
        searchKasirInputLabel = new javax.swing.JLabel();
        searchKasirInputTextField = new javax.swing.JTextField();
        searchKasirInputButton = new javax.swing.JButton();
        kasirFormPanel = new javax.swing.JPanel();
        kasirButtonPanel = new javax.swing.JPanel();
        barukanKasirButton = new javax.swing.JButton();
        hapusKasirButton = new javax.swing.JButton();
        tambahKasirButton = new javax.swing.JButton();
        namaKasirPanel = new javax.swing.JPanel();
        namaKasirInputLabel = new javax.swing.JLabel();
        namaKasirInputTextField = new javax.swing.JTextField();
        nomorLoketInputPanel = new javax.swing.JPanel();
        nomorLoketInputLabel = new javax.swing.JLabel();
        nomorLoketInputTextField = new javax.swing.JTextField();
        shiftInputPanel = new javax.swing.JPanel();
        shiftInputaLabel = new javax.swing.JLabel();
        shiftInputScrollPanel = new javax.swing.JScrollPane();
        shiftInputTextArea = new javax.swing.JTextArea();
        simpanKasirButton = new javax.swing.JButton();
        kasirScrollPanel = new javax.swing.JScrollPane();
        kasirTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKasirInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKasirInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKasirInputLabel.setText("Pencarian Kasir");

        searchKasirInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKasirInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKasirInputTextFieldKeyTyped(evt);
            }
        });

        searchKasirInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchKasirInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKasirInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKasirInputButton.setText("Cari");
        searchKasirInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKasirInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchKasirInputPanelLayout = new javax.swing.GroupLayout(searchKasirInputPanel);
        searchKasirInputPanel.setLayout(searchKasirInputPanelLayout);
        searchKasirInputPanelLayout.setHorizontalGroup(
            searchKasirInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKasirInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchKasirInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKasirInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchKasirInputPanelLayout.createSequentialGroup()
                        .addComponent(searchKasirInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKasirInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchKasirInputPanelLayout.setVerticalGroup(
            searchKasirInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKasirInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKasirInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKasirInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchKasirInputTextField)
                    .addComponent(searchKasirInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kasirFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        kasirFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        kasirButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanKasirButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKasirButton.setText("Barukan");
        barukanKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKasirButtonActionPerformed(evt);
            }
        });

        hapusKasirButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKasirButton.setText("Hapus");
        hapusKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKasirButtonActionPerformed(evt);
            }
        });

        tambahKasirButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahKasirButton.setText("Tambah");
        tambahKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKasirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kasirButtonPanelLayout = new javax.swing.GroupLayout(kasirButtonPanel);
        kasirButtonPanel.setLayout(kasirButtonPanelLayout);
        kasirButtonPanelLayout.setHorizontalGroup(
            kasirButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKasirButton)
                .addGap(18, 18, 18)
                .addComponent(barukanKasirButton)
                .addGap(18, 18, 18)
                .addComponent(hapusKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        kasirButtonPanelLayout.setVerticalGroup(
            kasirButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasirButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahKasirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusKasirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaKasirPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaKasirPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaKasirInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaKasirInputLabel.setText("Nama Kasir");

        namaKasirInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaKasirInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaKasirInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaKasirPanelLayout = new javax.swing.GroupLayout(namaKasirPanel);
        namaKasirPanel.setLayout(namaKasirPanelLayout);
        namaKasirPanelLayout.setHorizontalGroup(
            namaKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKasirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKasirInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaKasirInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaKasirPanelLayout.setVerticalGroup(
            namaKasirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKasirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKasirInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKasirInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomorLoketInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        nomorLoketInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        nomorLoketInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorLoketInputLabel.setText("Nomor Loket");

        nomorLoketInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout nomorLoketInputPanelLayout = new javax.swing.GroupLayout(nomorLoketInputPanel);
        nomorLoketInputPanel.setLayout(nomorLoketInputPanelLayout);
        nomorLoketInputPanelLayout.setHorizontalGroup(
            nomorLoketInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorLoketInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorLoketInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorLoketInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorLoketInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nomorLoketInputPanelLayout.setVerticalGroup(
            nomorLoketInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorLoketInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomorLoketInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorLoketInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shiftInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        shiftInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        shiftInputaLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        shiftInputaLabel.setText("Shift");

        shiftInputTextArea.setColumns(20);
        shiftInputTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        shiftInputTextArea.setRows(5);
        shiftInputScrollPanel.setViewportView(shiftInputTextArea);

        javax.swing.GroupLayout shiftInputPanelLayout = new javax.swing.GroupLayout(shiftInputPanel);
        shiftInputPanel.setLayout(shiftInputPanelLayout);
        shiftInputPanelLayout.setHorizontalGroup(
            shiftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shiftInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shiftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shiftInputPanelLayout.createSequentialGroup()
                        .addComponent(shiftInputaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addComponent(shiftInputScrollPanel))
                .addContainerGap())
        );
        shiftInputPanelLayout.setVerticalGroup(
            shiftInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shiftInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shiftInputaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shiftInputScrollPanel)
                .addContainerGap())
        );

        simpanKasirButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanKasirButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKasirButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKasirButton.setText("Simpan");
        simpanKasirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKasirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kasirFormPanelLayout = new javax.swing.GroupLayout(kasirFormPanel);
        kasirFormPanel.setLayout(kasirFormPanelLayout);
        kasirFormPanelLayout.setHorizontalGroup(
            kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kasirFormPanelLayout.createSequentialGroup()
                        .addGroup(kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomorLoketInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaKasirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(shiftInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kasirFormPanelLayout.createSequentialGroup()
                        .addComponent(kasirButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kasirFormPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kasirFormPanelLayout.setVerticalGroup(
            kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kasirFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kasirButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kasirFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kasirFormPanelLayout.createSequentialGroup()
                        .addComponent(namaKasirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorLoketInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shiftInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(simpanKasirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kasirScrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        kasirTextArea.setColumns(20);
        kasirTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        kasirTextArea.setRows(5);
        kasirScrollPanel.setViewportView(kasirTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKasirInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(kasirFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(kasirScrollPanel))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKasirInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kasirFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(kasirScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchKasirInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKasirInputTextFieldKeyTyped
        if (evt.getKeyChar() == '\n') {
            doSearchKasir();
        }
    }//GEN-LAST:event_searchKasirInputTextFieldKeyTyped

    private void searchKasirInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKasirInputButtonActionPerformed
        doSearchKasir();
        setComponentsKasir(false);
    }//GEN-LAST:event_searchKasirInputButtonActionPerformed

    private void barukanKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKasirButtonActionPerformed
        actionKasir = "update";
        setComponentsKasir(true);
    }//GEN-LAST:event_barukanKasirButtonActionPerformed

    private void hapusKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKasirButtonActionPerformed

        setComponentsKasir(false);
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION) {
            idKasir = -1;
            return;
        }
        clearTextKasir();
        setEditDeleteButtonKasir(false);
        setComponentsKasir(false);

        kk.deleteDataKasir(idKasir);
        idKasir = -1;
        showKasir();
    }//GEN-LAST:event_hapusKasirButtonActionPerformed

    private void tambahKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKasirButtonActionPerformed
        actionKasir = "add";
        clearTextKasir();
        setEditDeleteButtonKasir(false);
        setComponentsKasir(true);
    }//GEN-LAST:event_tambahKasirButtonActionPerformed

    private void namaKasirInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaKasirInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaKasirInputTextFieldActionPerformed

    private void simpanKasirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKasirButtonActionPerformed
        // TODO add your handling code here:
        if (actionKasir == null) {
            return;
        }
        try {
            inputKosongKasirException();
//            noTelponException();
            if (JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionKasir + "?") == JOptionPane.CLOSED_OPTION) {
                return;
            }
            k = new Kasir(namaKasirInputTextField.getText(), shiftInputTextArea.getText(), Integer.parseInt(nomorLoketInputTextField.getText()));
            switch (actionKasir) {
                case "add":
                    kk.insertDataKasir(k);
                    clearTextKasir();
                    setEditDeleteButtonKasir(false);
                    setComponentsKasir(false);
                    break;
                case "update":
                    kk.updateDataKasir(k, idKasir);
                    clearTextKasir();
                    setEditDeleteButtonKasir(false);
                    setComponentsKasir(false);
                    break;
                default:
                    break;
            }
            showKasir();
            actionKasir = null;
        } catch (InputKosongException e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Input Tidak Boleh Kosong!!");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Input Angka Salah!!");
        };
    }//GEN-LAST:event_simpanKasirButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanKasirButton;
    private javax.swing.JButton hapusKasirButton;
    private javax.swing.JPanel kasirButtonPanel;
    private javax.swing.JPanel kasirFormPanel;
    private javax.swing.JScrollPane kasirScrollPanel;
    private javax.swing.JTextArea kasirTextArea;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaKasirInputLabel;
    private javax.swing.JTextField namaKasirInputTextField;
    private javax.swing.JPanel namaKasirPanel;
    private javax.swing.JLabel nomorLoketInputLabel;
    private javax.swing.JPanel nomorLoketInputPanel;
    private javax.swing.JTextField nomorLoketInputTextField;
    private javax.swing.JButton searchKasirInputButton;
    private javax.swing.JLabel searchKasirInputLabel;
    private javax.swing.JPanel searchKasirInputPanel;
    private javax.swing.JTextField searchKasirInputTextField;
    private javax.swing.JPanel shiftInputPanel;
    private javax.swing.JScrollPane shiftInputScrollPanel;
    private javax.swing.JTextArea shiftInputTextArea;
    private javax.swing.JLabel shiftInputaLabel;
    private javax.swing.JButton simpanKasirButton;
    private javax.swing.JButton tambahKasirButton;
    // End of variables declaration//GEN-END:variables
}
