/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import Exception.InputKosongException;
import Exception.InputSpecialAtributeException;
import control.PaketServisControl;
import control.PaketRinganControl;
import control.PaketLengkapControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import model.PaketServis;
import model.PaketRingan;
import model.PaketLengkap;

public class PaketServisMainPanel extends javax.swing.JPanel {

    private PaketServisControl psC = new PaketServisControl();
    private PaketLengkapControl plC = new PaketLengkapControl();
    private PaketRinganControl prC = new PaketRinganControl();
    private PaketServis ps = null;
    private PaketRingan pR = null;
    private PaketLengkap pL = null;
    String action = null;
    int idCustomer = 0;
    private Component rootPane;

    public PaketServisMainPanel() {
        initComponents();
        setOpaque(false);
        showPaketServis();
        setComponentsPaketServis(false);
        setPaketServisEditDeleteButton(false);
        clearText();
    }

    public void inputKosongPaketServisException() throws InputKosongException {
        if (namaPaketServisInputTextField.getText().isEmpty() || durasiPaketServisInputTextfield.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }


    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public void setComponentsPaketServis(boolean value) {
        idPaketServisInputTextField.setEnabled(value);
        namaPaketServisInputTextField.setEnabled(value);
        durasiPaketServisInputTextfield.setEnabled(value);
        jenisPaketServisInputButton.setEnabled(value);
        specialAtributeInputTextfield.setEnabled(value);
    }

    public void setPaketServisEditDeleteButton(boolean value) {
        barukanPaketServisButton.setEnabled(value);
        hapusPaketServisButton.setEnabled(value);
    }

    public void clearText() {
        idPaketServisInputTextField.setText("");
        namaPaketServisInputTextField.setText("");
        durasiPaketServisInputTextfield.setText("");
        jenisPaketServisInputButton.setText("");
        searchPaketServisInputTextField.setText("");
        specialAtributeInputTextfield.setText("");
//        specialAtributeInputLabel.setText("");
    }

    public void showPaketServis() {
        paketLengkapTextArea.setText("List PaketLengkap: \n ============= \n" + plC.showString());
        paketRinganTextArea.setText("List PaketRingan: \n ============= \n" + prC.showString());
    }



    private void doSearchPaketServis() {
        if (searchPaketServisInputTextField.getText().isEmpty()) {
            return;
        }

        ps = psC.search(searchPaketServisInputTextField.getText());

        if (ps != null) {
            setPaketServisEditDeleteButton(true);
            idPaketServisInputTextField.setText(ps.getId());
            namaPaketServisInputTextField.setText(ps.getNama());
            durasiPaketServisInputTextfield.setText(Integer.toString(ps.getDurasi()));
            jenisPaketServisInputButton.setText(ps.getJenis());
            setSpecialAtributeLabel();
            specialAtributeInputTextfield.setText(ps.getSpecial());
        } else {
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
        }
    }

    private void setSpecialAtributeLabel() {
        if (jenisPaketServisInputButton.getText().equals("Ringan")) {
            specialAtributeInputLabel.setText("Layanan Tambahan");
        } else {
            specialAtributeInputLabel.setText("Fasilitas Paket");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchPaketServisInputPanel = new javax.swing.JPanel();
        searchPaketServisLabel = new javax.swing.JLabel();
        searchPaketServisInputTextField = new javax.swing.JTextField();
        searchPaketServisInputButton = new javax.swing.JButton();
        paketServisFormPanel = new javax.swing.JPanel();
        paketServisButtonPanel = new javax.swing.JPanel();
        barukanPaketServisButton = new javax.swing.JButton();
        hapusPaketServisButton = new javax.swing.JButton();
        tambahPaketServisButton = new javax.swing.JButton();
        idPaketServisInputPanel = new javax.swing.JPanel();
        idPaketServisInputLabel = new javax.swing.JLabel();
        idPaketServisInputTextField = new javax.swing.JTextField();
        namaPaketServisInputPanel = new javax.swing.JPanel();
        namaPaketServisInputLabel = new javax.swing.JLabel();
        namaPaketServisInputTextField = new javax.swing.JTextField();
        durasiPaketServisInputPanel = new javax.swing.JPanel();
        durasiPaketServisInputLabel = new javax.swing.JLabel();
        durasiPaketServisInputTextfield = new javax.swing.JTextField();
        specialAtributeInputPanel = new javax.swing.JPanel();
        specialAtributeInputLabel = new javax.swing.JLabel();
        specialAtributeInputTextfield = new javax.swing.JTextField();
        jenisPaketServisInputPanel = new javax.swing.JPanel();
        jenisPaketServisInputLabel = new javax.swing.JLabel();
        jenisPaketServisInputButton = new javax.swing.JButton();
        simpanPaketServisButton = new javax.swing.JButton();
        paketLengkapScrollPane = new javax.swing.JScrollPane();
        paketLengkapTextArea = new javax.swing.JTextArea();
        paketRinganScrollPane = new javax.swing.JScrollPane();
        paketRinganTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchPaketServisInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchPaketServisInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchPaketServisLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPaketServisLabel.setText("Pencarian Paket Servis");

        searchPaketServisInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPaketServisInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPaketServisInputTextFieldActionPerformed(evt);
            }
        });
        searchPaketServisInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchPaketServisInputTextFieldKeyPressed(evt);
            }
        });

        searchPaketServisInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchPaketServisInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchPaketServisInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchPaketServisInputButton.setText("Cari");
        searchPaketServisInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPaketServisInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPaketServisInputPanelLayout = new javax.swing.GroupLayout(searchPaketServisInputPanel);
        searchPaketServisInputPanel.setLayout(searchPaketServisInputPanelLayout);
        searchPaketServisInputPanelLayout.setHorizontalGroup(
            searchPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPaketServisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchPaketServisInputPanelLayout.createSequentialGroup()
                        .addComponent(searchPaketServisInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchPaketServisInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchPaketServisInputPanelLayout.setVerticalGroup(
            searchPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPaketServisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchPaketServisInputTextField)
                    .addComponent(searchPaketServisInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paketServisFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        paketServisButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanPaketServisButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanPaketServisButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanPaketServisButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanPaketServisButton.setText("Barukan");
        barukanPaketServisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanPaketServisButtonActionPerformed(evt);
            }
        });

        hapusPaketServisButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusPaketServisButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusPaketServisButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusPaketServisButton.setText("Hapus");
        hapusPaketServisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPaketServisButtonActionPerformed(evt);
            }
        });

        tambahPaketServisButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahPaketServisButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahPaketServisButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahPaketServisButton.setText("Tambah");
        tambahPaketServisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahPaketServisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paketServisButtonPanelLayout = new javax.swing.GroupLayout(paketServisButtonPanel);
        paketServisButtonPanel.setLayout(paketServisButtonPanelLayout);
        paketServisButtonPanelLayout.setHorizontalGroup(
            paketServisButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketServisButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahPaketServisButton)
                .addGap(18, 18, 18)
                .addComponent(barukanPaketServisButton)
                .addGap(18, 18, 18)
                .addComponent(hapusPaketServisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        paketServisButtonPanelLayout.setVerticalGroup(
            paketServisButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketServisButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paketServisButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanPaketServisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahPaketServisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusPaketServisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idPaketServisInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        idPaketServisInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPaketServisInputLabel.setText("ID Paket Servis");

        idPaketServisInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idPaketServisInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPaketServisInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPaketServisInputPanelLayout = new javax.swing.GroupLayout(idPaketServisInputPanel);
        idPaketServisInputPanel.setLayout(idPaketServisInputPanelLayout);
        idPaketServisInputPanelLayout.setHorizontalGroup(
            idPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idPaketServisInputTextField)
                    .addComponent(idPaketServisInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idPaketServisInputPanelLayout.setVerticalGroup(
            idPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idPaketServisInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPaketServisInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaPaketServisInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaPaketServisInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaPaketServisInputLabel.setText("Nama");

        namaPaketServisInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaPaketServisInputPanelLayout = new javax.swing.GroupLayout(namaPaketServisInputPanel);
        namaPaketServisInputPanel.setLayout(namaPaketServisInputPanelLayout);
        namaPaketServisInputPanelLayout.setHorizontalGroup(
            namaPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaPaketServisInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(namaPaketServisInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPaketServisInputPanelLayout.setVerticalGroup(
            namaPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaPaketServisInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPaketServisInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        durasiPaketServisInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        durasiPaketServisInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        durasiPaketServisInputLabel.setText("Durasi Pengerjaan");

        durasiPaketServisInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        durasiPaketServisInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                durasiPaketServisInputTextfieldKeyTyped(evt);
            }
        });

        specialAtributeInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        specialAtributeInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputLabel.setForeground(new java.awt.Color(0, 0, 0));
        specialAtributeInputLabel.setText("Fasilitas Paket");

        specialAtributeInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                specialAtributeInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout specialAtributeInputPanelLayout = new javax.swing.GroupLayout(specialAtributeInputPanel);
        specialAtributeInputPanel.setLayout(specialAtributeInputPanelLayout);
        specialAtributeInputPanelLayout.setHorizontalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specialAtributeInputTextfield)
                    .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                        .addComponent(specialAtributeInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        specialAtributeInputPanelLayout.setVerticalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specialAtributeInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialAtributeInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout durasiPaketServisInputPanelLayout = new javax.swing.GroupLayout(durasiPaketServisInputPanel);
        durasiPaketServisInputPanel.setLayout(durasiPaketServisInputPanelLayout);
        durasiPaketServisInputPanelLayout.setHorizontalGroup(
            durasiPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durasiPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(durasiPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(durasiPaketServisInputTextfield)
                    .addComponent(durasiPaketServisInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        durasiPaketServisInputPanelLayout.setVerticalGroup(
            durasiPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durasiPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(durasiPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(durasiPaketServisInputPanelLayout.createSequentialGroup()
                        .addComponent(durasiPaketServisInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(durasiPaketServisInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jenisPaketServisInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        jenisPaketServisInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisPaketServisInputLabel.setText("Jenis Paket Servis");

        jenisPaketServisInputButton.setBackground(new java.awt.Color(153, 204, 255));
        jenisPaketServisInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisPaketServisInputButton.setText("Ringan");
        jenisPaketServisInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisPaketServisInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jenisPaketServisInputPanelLayout = new javax.swing.GroupLayout(jenisPaketServisInputPanel);
        jenisPaketServisInputPanel.setLayout(jenisPaketServisInputPanelLayout);
        jenisPaketServisInputPanelLayout.setHorizontalGroup(
            jenisPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisPaketServisInputPanelLayout.createSequentialGroup()
                        .addComponent(jenisPaketServisInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jenisPaketServisInputPanelLayout.createSequentialGroup()
                        .addComponent(jenisPaketServisInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jenisPaketServisInputPanelLayout.setVerticalGroup(
            jenisPaketServisInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisPaketServisInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisPaketServisInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisPaketServisInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        simpanPaketServisButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanPaketServisButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanPaketServisButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanPaketServisButton.setText("Simpan");
        simpanPaketServisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPaketServisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paketServisFormPanelLayout = new javax.swing.GroupLayout(paketServisFormPanel);
        paketServisFormPanel.setLayout(paketServisFormPanelLayout);
        paketServisFormPanelLayout.setHorizontalGroup(
            paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketServisFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paketServisButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paketServisFormPanelLayout.createSequentialGroup()
                        .addGroup(paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaPaketServisInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idPaketServisInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paketServisFormPanelLayout.createSequentialGroup()
                                .addComponent(jenisPaketServisInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(419, 419, 419)
                                .addComponent(simpanPaketServisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(durasiPaketServisInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        paketServisFormPanelLayout.setVerticalGroup(
            paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketServisFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paketServisButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paketServisFormPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idPaketServisInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durasiPaketServisInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paketServisFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPaketServisInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jenisPaketServisInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paketServisFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanPaketServisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        paketLengkapScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        paketLengkapScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        paketLengkapTextArea.setColumns(20);
        paketLengkapTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        paketLengkapTextArea.setRows(5);
        paketLengkapScrollPane.setViewportView(paketLengkapTextArea);

        paketRinganScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        paketRinganTextArea.setColumns(20);
        paketRinganTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        paketRinganTextArea.setRows(5);
        paketRinganTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        paketRinganScrollPane.setViewportView(paketRinganTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPaketServisInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paketServisFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(paketRinganScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paketLengkapScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPaketServisInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paketServisFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paketRinganScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(paketLengkapScrollPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchPaketServisInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchPaketServisInputTextFieldKeyPressed

    }//GEN-LAST:event_searchPaketServisInputTextFieldKeyPressed

    private void searchPaketServisInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPaketServisInputButtonActionPerformed
        doSearchPaketServis();
    }//GEN-LAST:event_searchPaketServisInputButtonActionPerformed

    private void barukanPaketServisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanPaketServisButtonActionPerformed
        action = "update";
        setComponentsPaketServis(true);
        idPaketServisInputTextField.setEnabled(false);
    }//GEN-LAST:event_barukanPaketServisButtonActionPerformed

    private void hapusPaketServisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPaketServisButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION) {
            return;
        }

        psC.delete(idPaketServisInputTextField.getText());
        clearText();
        setPaketServisEditDeleteButton(false);
        setComponentsPaketServis(false);
        showPaketServis();
    }//GEN-LAST:event_hapusPaketServisButtonActionPerformed

    private void tambahPaketServisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahPaketServisButtonActionPerformed
        action = "add";
        clearText();
        setPaketServisEditDeleteButton(false);
        setComponentsPaketServis(true);
        setPaketServisEditDeleteButton(false);

        idPaketServisInputTextField.setEnabled(false);
        idPaketServisInputTextField.setText(psC.generateId());
        jenisPaketServisInputButton.setText("Ringan");
        setSpecialAtributeLabel();
    }//GEN-LAST:event_tambahPaketServisButtonActionPerformed

    private void idPaketServisInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPaketServisInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPaketServisInputTextFieldActionPerformed

    private void durasiPaketServisInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durasiPaketServisInputTextfieldKeyTyped

    }//GEN-LAST:event_durasiPaketServisInputTextfieldKeyTyped

    private void jenisPaketServisInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisPaketServisInputButtonActionPerformed
        switch (jenisPaketServisInputButton.getText()) {
            case "Ringan":
                jenisPaketServisInputButton.setText("Lengkap");
                break;
            case "Lengkap":
                jenisPaketServisInputButton.setText("Ringan");
                break;
        }
        setSpecialAtributeLabel();
    }//GEN-LAST:event_jenisPaketServisInputButtonActionPerformed

    private void simpanPaketServisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPaketServisButtonActionPerformed
        if (action == null) {
            return;
        }
        try {
            inputKosongPaketServisException();

            if (JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + action + "?") == JOptionPane.CLOSED_OPTION) {
                return;
            }

            switch (action) {
                case "add":
                    if (jenisPaketServisInputButton.getText().equals("Ringan")) {
                        pR = new PaketRingan(
                                idPaketServisInputTextField.getText(),
                                namaPaketServisInputTextField.getText(),
                                jenisPaketServisInputButton.getText(),
                                Integer.parseInt(durasiPaketServisInputTextfield.getText()),
                                specialAtributeInputLabel.getText()
                        );
                        prC.insert(pR);
                    } else {
                        pL = new PaketLengkap(
                                idPaketServisInputTextField.getText(),
                                namaPaketServisInputTextField.getText(),
                                jenisPaketServisInputButton.getText(),
                                Integer.parseInt(durasiPaketServisInputTextfield.getText()),
                                specialAtributeInputLabel.getText()
                        );
                        plC.insert(pL);
                    }
                    clearText();
                    setPaketServisEditDeleteButton(false);
                    setComponentsPaketServis(false);
                    showPaketServis();
                    break;
                case "update":
                    if (jenisPaketServisInputButton.getText().equals("Ringan")) {
                        pR = new PaketRingan(
                                idPaketServisInputTextField.getText(),
                                namaPaketServisInputTextField.getText(),
                                jenisPaketServisInputButton.getText(),
                                Integer.parseInt(durasiPaketServisInputTextfield.getText()),
                                specialAtributeInputLabel.getText()
                        );
                        prC.update(pR);
                    } else {
                        pL = new PaketLengkap(
                                idPaketServisInputTextField.getText(),
                                namaPaketServisInputTextField.getText(),
                                jenisPaketServisInputButton.getText(),
                                Integer.parseInt(durasiPaketServisInputTextfield.getText()),
                                specialAtributeInputLabel.getText()
                        );
                        plC.update(pL);
                    }
                    
                    clearText();
                    setPaketServisEditDeleteButton(false);
                    setComponentsPaketServis(false);
                    showPaketServis();
                    break;
                default:
                    break;
            }
            action = null;
        } catch (InputKosongException e) {
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Input Salah!");
        }
    }//GEN-LAST:event_simpanPaketServisButtonActionPerformed

    private void specialAtributeInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_specialAtributeInputTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_specialAtributeInputTextfieldKeyTyped

    private void searchPaketServisInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPaketServisInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPaketServisInputTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanPaketServisButton;
    private javax.swing.JLabel durasiPaketServisInputLabel;
    private javax.swing.JPanel durasiPaketServisInputPanel;
    private javax.swing.JTextField durasiPaketServisInputTextfield;
    private javax.swing.JButton hapusPaketServisButton;
    private javax.swing.JLabel idPaketServisInputLabel;
    private javax.swing.JPanel idPaketServisInputPanel;
    private javax.swing.JTextField idPaketServisInputTextField;
    private javax.swing.JButton jenisPaketServisInputButton;
    private javax.swing.JLabel jenisPaketServisInputLabel;
    private javax.swing.JPanel jenisPaketServisInputPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namaPaketServisInputLabel;
    private javax.swing.JPanel namaPaketServisInputPanel;
    private javax.swing.JTextField namaPaketServisInputTextField;
    private javax.swing.JScrollPane paketLengkapScrollPane;
    private javax.swing.JTextArea paketLengkapTextArea;
    private javax.swing.JScrollPane paketRinganScrollPane;
    private javax.swing.JTextArea paketRinganTextArea;
    private javax.swing.JPanel paketServisButtonPanel;
    private javax.swing.JPanel paketServisFormPanel;
    private javax.swing.JButton searchPaketServisInputButton;
    private javax.swing.JPanel searchPaketServisInputPanel;
    private javax.swing.JTextField searchPaketServisInputTextField;
    private javax.swing.JLabel searchPaketServisLabel;
    private javax.swing.JButton simpanPaketServisButton;
    private javax.swing.JLabel specialAtributeInputLabel;
    private javax.swing.JPanel specialAtributeInputPanel;
    private javax.swing.JTextField specialAtributeInputTextfield;
    private javax.swing.JButton tambahPaketServisButton;
    // End of variables declaration//GEN-END:variables
}
