/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import Exception.InputKosongException;
import Exception.NoTelponException;
import control.CustomerControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import model.Customer;



public class CustomerMainPanel extends javax.swing.JPanel {
    private CustomerControl cc = new CustomerControl();
    private Customer c = null;
    String actionCustomer = null;
    int idCustomer = 0;
    private Component rootPane;
    
    
    private void inputKosongCustomerException() throws InputKosongException{
        if(namaCustomerInputTextField.getText().isEmpty() || alamatInputTextField.getText().isEmpty() || nomorTeleponInputTextField.getText().isEmpty())
            throw new InputKosongException();
    }
    
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
            
    private void noTelponException() throws NoTelponException{
        if(!nomorTeleponInputTextField.getText().matches("^\\+?[0-9]+$"))
            throw new NoTelponException();
    }
    
    public CustomerMainPanel() {
        initComponents();
        setOpaque(false);
        showCustomer();
        setComponentsCustomer(false);        
        setEditDeleteButtonCustomer(false);        
        clearTextCustomer();
    }
    
    // Customer Set Komponen
    public void setComponentsCustomer(boolean value){
        namaCustomerInputTextField.setEnabled(value);
        nomorTeleponInputTextField.setEnabled(value);
        alamatInputTextField.setEnabled(value);
    }
    
    // Customer Set Edit Delete Button
    public void setEditDeleteButtonCustomer(boolean value){
        barukanCustomerButton.setEnabled(value);
        hapusCustomerButton.setEnabled(value);
    }
    
    // Customer Clear Text
    public void clearTextCustomer(){
        namaCustomerInputTextField.setText("");
        nomorTeleponInputTextField.setText("");
        alamatInputTextField.setText("");
        searchCustomerInputTextField.setText("");
    }
    
    public void showCustomer(){
        customerTextArea.setText("List Customer: \n ============= \n"+cc.showAllStringCustomer());
    }

    private void doSearchCustomer(){
        if(searchCustomerInputTextField.getText().isEmpty())
            return;
            Customer c = cc.searchCustomerById(Integer.parseInt(searchCustomerInputTextField.getText()));
            if(c == null ){
                JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
                return;
            }
            setEditDeleteButtonCustomer(true);
            clearTextCustomer();
            
            namaCustomerInputTextField.setText(c.getNama());
            nomorTeleponInputTextField.setText(c.getAlamat());
            alamatInputTextField.setText(c.getNo_telepon());
            
            idCustomer = c.getId_customer();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchCustomerInputPanel = new javax.swing.JPanel();
        searchCustomerInputLabel = new javax.swing.JLabel();
        searchCustomerInputTextField = new javax.swing.JTextField();
        searchCustomerInputButton = new javax.swing.JButton();
        customerFormPanel = new javax.swing.JPanel();
        customerButtonPanel = new javax.swing.JPanel();
        barukanCustomerButton = new javax.swing.JButton();
        hapusCustomerButton = new javax.swing.JButton();
        tambahCustomerButton = new javax.swing.JButton();
        namaCustomerPanel = new javax.swing.JPanel();
        namaCustomerInputLabel = new javax.swing.JLabel();
        namaCustomerInputTextField = new javax.swing.JTextField();
        nomorTeleponInputPanel = new javax.swing.JPanel();
        nomorTeleponInputLabel = new javax.swing.JLabel();
        nomorTeleponInputTextField = new javax.swing.JTextField();
        alamatInputPanel1 = new javax.swing.JPanel();
        alamatInputLabel1 = new javax.swing.JLabel();
        alamatScrollPane = new javax.swing.JScrollPane();
        alamatInputTextField = new javax.swing.JTextArea();
        simpanCustomerButton = new javax.swing.JButton();
        mobilScrollPane1 = new javax.swing.JScrollPane();
        customerTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchCustomerInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchCustomerInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputLabel.setText("Pencarian Customer");

        searchCustomerInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchCustomerInputTextFieldKeyTyped(evt);
            }
        });

        searchCustomerInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchCustomerInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchCustomerInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchCustomerInputButton.setText("Cari");
        searchCustomerInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchCustomerInputPanelLayout = new javax.swing.GroupLayout(searchCustomerInputPanel);
        searchCustomerInputPanel.setLayout(searchCustomerInputPanelLayout);
        searchCustomerInputPanelLayout.setHorizontalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                        .addComponent(searchCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchCustomerInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchCustomerInputPanelLayout.setVerticalGroup(
            searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchCustomerInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchCustomerInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchCustomerInputTextField)
                    .addComponent(searchCustomerInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        customerFormPanel.setForeground(new java.awt.Color(255, 255, 255));

        customerButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanCustomerButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanCustomerButton.setText("Barukan");
        barukanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanCustomerButtonActionPerformed(evt);
            }
        });

        hapusCustomerButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusCustomerButton.setText("Hapus");
        hapusCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusCustomerButtonActionPerformed(evt);
            }
        });

        tambahCustomerButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahCustomerButton.setText("Tambah");
        tambahCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahCustomerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerButtonPanelLayout = new javax.swing.GroupLayout(customerButtonPanel);
        customerButtonPanel.setLayout(customerButtonPanelLayout);
        customerButtonPanelLayout.setHorizontalGroup(
            customerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(barukanCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(hapusCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        customerButtonPanelLayout.setVerticalGroup(
            customerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusCustomerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaCustomerPanel.setBackground(new java.awt.Color(255, 255, 255));
        namaCustomerPanel.setForeground(new java.awt.Color(255, 255, 255));

        namaCustomerInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaCustomerInputLabel.setText("Nama Customer");

        namaCustomerInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaCustomerInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaCustomerInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaCustomerPanelLayout = new javax.swing.GroupLayout(namaCustomerPanel);
        namaCustomerPanel.setLayout(namaCustomerPanelLayout);
        namaCustomerPanelLayout.setHorizontalGroup(
            namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaCustomerInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaCustomerPanelLayout.setVerticalGroup(
            namaCustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaCustomerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaCustomerInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaCustomerInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nomorTeleponInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        nomorTeleponInputPanel.setForeground(new java.awt.Color(255, 255, 255));

        nomorTeleponInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        nomorTeleponInputLabel.setText("Nomor Telepon");

        nomorTeleponInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout nomorTeleponInputPanelLayout = new javax.swing.GroupLayout(nomorTeleponInputPanel);
        nomorTeleponInputPanel.setLayout(nomorTeleponInputPanelLayout);
        nomorTeleponInputPanelLayout.setHorizontalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomorTeleponInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nomorTeleponInputPanelLayout.setVerticalGroup(
            nomorTeleponInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorTeleponInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomorTeleponInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomorTeleponInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        alamatInputPanel1.setBackground(new java.awt.Color(255, 255, 255));
        alamatInputPanel1.setForeground(new java.awt.Color(255, 255, 255));

        alamatInputLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputLabel1.setText("Alamat");

        alamatInputTextField.setColumns(20);
        alamatInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        alamatInputTextField.setRows(5);
        alamatScrollPane.setViewportView(alamatInputTextField);

        javax.swing.GroupLayout alamatInputPanel1Layout = new javax.swing.GroupLayout(alamatInputPanel1);
        alamatInputPanel1.setLayout(alamatInputPanel1Layout);
        alamatInputPanel1Layout.setHorizontalGroup(
            alamatInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alamatInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alamatInputPanel1Layout.createSequentialGroup()
                        .addComponent(alamatInputLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 175, Short.MAX_VALUE))
                    .addComponent(alamatScrollPane))
                .addContainerGap())
        );
        alamatInputPanel1Layout.setVerticalGroup(
            alamatInputPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alamatInputPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(alamatInputLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alamatScrollPane)
                .addContainerGap())
        );

        javax.swing.GroupLayout customerFormPanelLayout = new javax.swing.GroupLayout(customerFormPanel);
        customerFormPanel.setLayout(customerFormPanelLayout);
        customerFormPanelLayout.setHorizontalGroup(
            customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerFormPanelLayout.createSequentialGroup()
                        .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaCustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(alamatInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(customerFormPanelLayout.createSequentialGroup()
                        .addComponent(customerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        customerFormPanelLayout.setVerticalGroup(
            customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(customerFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(customerFormPanelLayout.createSequentialGroup()
                        .addComponent(namaCustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorTeleponInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(alamatInputPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        simpanCustomerButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanCustomerButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanCustomerButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanCustomerButton.setText("Simpan");
        simpanCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanCustomerButtonActionPerformed(evt);
            }
        });

        mobilScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        customerTextArea.setColumns(20);
        customerTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        customerTextArea.setRows(5);
        mobilScrollPane1.setViewportView(customerTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(customerFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mobilScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1218, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchCustomerInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(simpanCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(mobilScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchCustomerInputTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchCustomerInputTextFieldKeyTyped
        if(evt.getKeyChar()=='\n'){
            doSearchCustomer();
        }
    }//GEN-LAST:event_searchCustomerInputTextFieldKeyTyped

    private void searchCustomerInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerInputButtonActionPerformed
        doSearchCustomer();
    }//GEN-LAST:event_searchCustomerInputButtonActionPerformed

    private void barukanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanCustomerButtonActionPerformed
        actionCustomer = "update";
        setComponentsCustomer(true);
    }//GEN-LAST:event_barukanCustomerButtonActionPerformed

    private void hapusCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusCustomerButtonActionPerformed
        clearTextCustomer();
        setEditDeleteButtonCustomer(false);
        setComponentsCustomer(false);
        
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION){
            idCustomer = -1;
            return;
        }
        
        cc.deleteDataCustomer(idCustomer);
        idCustomer = -1;
        showCustomer();
    }//GEN-LAST:event_hapusCustomerButtonActionPerformed

    private void tambahCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahCustomerButtonActionPerformed
        actionCustomer = "add";
        clearTextCustomer();
        setEditDeleteButtonCustomer(true);
        setComponentsCustomer(true);
    }//GEN-LAST:event_tambahCustomerButtonActionPerformed

    private void namaCustomerInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaCustomerInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaCustomerInputTextFieldActionPerformed

    private void simpanCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanCustomerButtonActionPerformed
        // TODO add your handling code here:
        if(actionCustomer == null)
            return;
        try{
            inputKosongCustomerException();
            noTelponException();
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionCustomer + "?") == JOptionPane.CLOSED_OPTION)
                return;
            switch(actionCustomer){
            case "add":
                c = new Customer(namaCustomerInputTextField.getText(), nomorTeleponInputTextField.getText(), alamatInputTextField.getText());
                cc.insertDataCustomer(c);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
            case "update":
                c = new Customer(namaCustomerInputTextField.getText(), nomorTeleponInputTextField.getText(), alamatInputTextField.getText());
                cc.updateDataCustomer(c, idCustomer);
                clearTextCustomer();
                setEditDeleteButtonCustomer(false);
                setComponentsCustomer(false);
                break;
            default:
                break;
        }
        showCustomer();
        actionCustomer = null;
        }catch(InputKosongException e){
            System.out.println(e);
        }catch(NoTelponException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        };
    }//GEN-LAST:event_simpanCustomerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatInputLabel1;
    private javax.swing.JPanel alamatInputPanel1;
    private javax.swing.JTextArea alamatInputTextField;
    private javax.swing.JScrollPane alamatScrollPane;
    private javax.swing.JButton barukanCustomerButton;
    private javax.swing.JPanel customerButtonPanel;
    private javax.swing.JPanel customerFormPanel;
    private javax.swing.JTextArea customerTextArea;
    private javax.swing.JButton hapusCustomerButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mobilScrollPane1;
    private javax.swing.JLabel namaCustomerInputLabel;
    private javax.swing.JTextField namaCustomerInputTextField;
    private javax.swing.JPanel namaCustomerPanel;
    private javax.swing.JLabel nomorTeleponInputLabel;
    private javax.swing.JPanel nomorTeleponInputPanel;
    private javax.swing.JTextField nomorTeleponInputTextField;
    private javax.swing.JButton searchCustomerInputButton;
    private javax.swing.JLabel searchCustomerInputLabel;
    private javax.swing.JPanel searchCustomerInputPanel;
    private javax.swing.JTextField searchCustomerInputTextField;
    private javax.swing.JButton simpanCustomerButton;
    private javax.swing.JButton tambahCustomerButton;
    // End of variables declaration//GEN-END:variables
}
