/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panelView;

import Exception.InputKosongException;
import Exception.InputSpecialAtributeException;
import control.KendaraanControl;
import control.MobilControl;
import control.MotorControl;
import java.awt.Component;
import javax.swing.JOptionPane;
import model.Kendaraan;
import model.Mobil;
import model.Motor;


public class KendaraanMainPanel extends javax.swing.JPanel {
    private KendaraanControl kc = new KendaraanControl();
    private MotorControl mtrc = new MotorControl();
    private MobilControl mblc = new MobilControl();
    private Kendaraan k = null;
    private Mobil mbl = null;
    private Motor mtr = null;
    String actionKendaraan = null;
    int idCustomer = 0;
    private Component rootPane;
    
    public KendaraanMainPanel() {
        initComponents();
        setOpaque(false);
        showKendaraan();
        setComponentsKendaraan(false);
        setKendaraanEditDeleteButton(false);
        clearText();        
    }
    
    public void inputKosongKendaraanException() throws InputKosongException{
        if(namaKendaraanInputTextField.getText().isEmpty() || hargaKendaraanInputTextfield.getText().isEmpty())
            throw new InputKosongException();
    }

    private void InputSpecialAtributeKendaraanException() throws InputSpecialAtributeException{
        if(jenisKendaraanInputButton.getText().equals("Motor") && !isInteger(specialAtributeInputTextfield.getText()))
            throw new InputSpecialAtributeException();
    }

    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public void setComponentsKendaraan(boolean value){
        idKendaraanInputTextField.setEnabled(value);
        namaKendaraanInputTextField.setEnabled(value);
        hargaKendaraanInputTextfield.setEnabled(value);
        jenisKendaraanInputButton.setEnabled(value);
    }
    
    public void setKendaraanEditDeleteButton(boolean value){
        barukanKendaraanButton.setEnabled(value);
        hapusKendaraanButton.setEnabled(value);
    }
    
    public void clearText(){
        idKendaraanInputTextField.setText("");
        namaKendaraanInputTextField.setText("");
        hargaKendaraanInputTextfield.setText("");
        jenisKendaraanInputButton.setText("");
        searchKendaraanInputTextField.setText("");
        specialAtributeInputTextfield.setText("");
        specialAtributeInputLabel.setText("");
    }
    
    public void showKendaraan(){
        motorTextArea.setText("List Motor: \n ============= \n"+mtrc.showStringKendaraan());
        mobilTextArea.setText("List Mobil: \n ============= \n"+mblc.showStringKendaraan());
    }

    private boolean mobilIsSelected(){
        return jenisKendaraanInputButton.getText().equals("Mobil");
    }
    
    private void doSearchKendaraan(){
        if(searchKendaraanInputTextField.getText().isEmpty())
            return;
        
            k = kc.searchDataKendaraan(searchKendaraanInputTextField.getText());
            
        if(k != null){
            setKendaraanEditDeleteButton(true);
            idKendaraanInputTextField.setText(k.getId_kendaraan());
            namaKendaraanInputTextField.setText(k.getNama());
            hargaKendaraanInputTextfield.setText(Float.toString(k.getHarga()));
            jenisKendaraanInputButton.setText(k.getJenis());
            setSpecialAtributeLabel();
            specialAtributeInputTextfield.setText(k.getSpecial());
        }else{
            JOptionPane.showMessageDialog(rootPane, "NOT FOUND !!!");
        }
    }

    private void setSpecialAtributeLabel(){
        if(jenisKendaraanInputButton.getText().equals("Mobil")){
            specialAtributeInputLabel.setText("Jenis Mesin");
        }else{
            specialAtributeInputLabel.setText("Jumlah Tak");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        searchKendaraanInputPanel = new javax.swing.JPanel();
        searchKendaraanInputLabel = new javax.swing.JLabel();
        searchKendaraanInputTextField = new javax.swing.JTextField();
        searchKendaraanInputButton = new javax.swing.JButton();
        simpanKendaraanButton = new javax.swing.JButton();
        kendaraanFormPanel = new javax.swing.JPanel();
        kendaraanButtonPanel = new javax.swing.JPanel();
        barukanKendaraanButton = new javax.swing.JButton();
        hapusKendaraanButton = new javax.swing.JButton();
        tambahKendaraanButton = new javax.swing.JButton();
        idKendaraanInputPanel = new javax.swing.JPanel();
        idKendaraanInputLabel = new javax.swing.JLabel();
        idKendaraanInputTextField = new javax.swing.JTextField();
        namaKendaraanInputPanel = new javax.swing.JPanel();
        namaKendaraanInputLabel = new javax.swing.JLabel();
        namaKendaraanInputTextField = new javax.swing.JTextField();
        hargaKendaraanInputPanel = new javax.swing.JPanel();
        hargaKendaraanInputLabel = new javax.swing.JLabel();
        hargaKendaraanInputTextfield = new javax.swing.JTextField();
        jenisKendaraanInputPanel = new javax.swing.JPanel();
        jenisKendaraanInputLabel = new javax.swing.JLabel();
        jenisKendaraanInputButton = new javax.swing.JButton();
        specialAtributeInputPanel = new javax.swing.JPanel();
        specialAtributeInputLabel = new javax.swing.JLabel();
        specialAtributeInputTextfield = new javax.swing.JTextField();
        motorScrollPane = new javax.swing.JScrollPane();
        motorTextArea = new javax.swing.JTextArea();
        mobilScrollPane = new javax.swing.JScrollPane();
        mobilTextArea = new javax.swing.JTextArea();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        searchKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));
        searchKendaraanInputPanel.setPreferredSize(new java.awt.Dimension(687, 65));

        searchKendaraanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKendaraanInputLabel.setText("Pencarian Kendaraan");

        searchKendaraanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKendaraanInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKendaraanInputTextFieldActionPerformed(evt);
            }
        });
        searchKendaraanInputTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKendaraanInputTextFieldKeyPressed(evt);
            }
        });

        searchKendaraanInputButton.setBackground(new java.awt.Color(27, 26, 85));
        searchKendaraanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        searchKendaraanInputButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKendaraanInputButton.setText("Cari");
        searchKendaraanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKendaraanInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchKendaraanInputPanelLayout = new javax.swing.GroupLayout(searchKendaraanInputPanel);
        searchKendaraanInputPanel.setLayout(searchKendaraanInputPanelLayout);
        searchKendaraanInputPanelLayout.setHorizontalGroup(
            searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKendaraanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                        .addComponent(searchKendaraanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchKendaraanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 532, Short.MAX_VALUE)))
                .addContainerGap())
        );
        searchKendaraanInputPanelLayout.setVerticalGroup(
            searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKendaraanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchKendaraanInputTextField)
                    .addComponent(searchKendaraanInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simpanKendaraanButton.setBackground(new java.awt.Color(51, 178, 73));
        simpanKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        simpanKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        simpanKendaraanButton.setText("Simpan");
        simpanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKendaraanButtonActionPerformed(evt);
            }
        });

        kendaraanFormPanel.setBackground(new java.awt.Color(255, 255, 255));

        kendaraanButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        barukanKendaraanButton.setBackground(new java.awt.Color(255, 189, 3));
        barukanKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        barukanKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        barukanKendaraanButton.setText("Barukan");
        barukanKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barukanKendaraanButtonActionPerformed(evt);
            }
        });

        hapusKendaraanButton.setBackground(new java.awt.Color(237, 8, 0));
        hapusKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hapusKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        hapusKendaraanButton.setText("Hapus");
        hapusKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusKendaraanButtonActionPerformed(evt);
            }
        });

        tambahKendaraanButton.setBackground(new java.awt.Color(51, 178, 73));
        tambahKendaraanButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        tambahKendaraanButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahKendaraanButton.setText("Tambah");
        tambahKendaraanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahKendaraanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kendaraanButtonPanelLayout = new javax.swing.GroupLayout(kendaraanButtonPanel);
        kendaraanButtonPanel.setLayout(kendaraanButtonPanelLayout);
        kendaraanButtonPanelLayout.setHorizontalGroup(
            kendaraanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambahKendaraanButton)
                .addGap(18, 18, 18)
                .addComponent(barukanKendaraanButton)
                .addGap(18, 18, 18)
                .addComponent(hapusKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        kendaraanButtonPanelLayout.setVerticalGroup(
            kendaraanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(barukanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahKendaraanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusKendaraanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        idKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        idKendaraanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idKendaraanInputLabel.setText("ID Kendaraan");

        idKendaraanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        idKendaraanInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idKendaraanInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idKendaraanInputPanelLayout = new javax.swing.GroupLayout(idKendaraanInputPanel);
        idKendaraanInputPanel.setLayout(idKendaraanInputPanelLayout);
        idKendaraanInputPanelLayout.setHorizontalGroup(
            idKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idKendaraanInputTextField)
                    .addComponent(idKendaraanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        idKendaraanInputPanelLayout.setVerticalGroup(
            idKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idKendaraanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idKendaraanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        namaKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        namaKendaraanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        namaKendaraanInputLabel.setText("Nama");

        namaKendaraanInputTextField.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N

        javax.swing.GroupLayout namaKendaraanInputPanelLayout = new javax.swing.GroupLayout(namaKendaraanInputPanel);
        namaKendaraanInputPanel.setLayout(namaKendaraanInputPanelLayout);
        namaKendaraanInputPanelLayout.setHorizontalGroup(
            namaKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaKendaraanInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(namaKendaraanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaKendaraanInputPanelLayout.setVerticalGroup(
            namaKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKendaraanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaKendaraanInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        hargaKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        hargaKendaraanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaKendaraanInputLabel.setText("Harga");

        hargaKendaraanInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        hargaKendaraanInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hargaKendaraanInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout hargaKendaraanInputPanelLayout = new javax.swing.GroupLayout(hargaKendaraanInputPanel);
        hargaKendaraanInputPanel.setLayout(hargaKendaraanInputPanelLayout);
        hargaKendaraanInputPanelLayout.setHorizontalGroup(
            hargaKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hargaKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hargaKendaraanInputTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(hargaKendaraanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hargaKendaraanInputPanelLayout.setVerticalGroup(
            hargaKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hargaKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hargaKendaraanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaKendaraanInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jenisKendaraanInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        jenisKendaraanInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisKendaraanInputLabel.setText("Jenis Kendaraan");

        jenisKendaraanInputButton.setBackground(new java.awt.Color(153, 204, 255));
        jenisKendaraanInputButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jenisKendaraanInputButton.setText("Mobil");
        jenisKendaraanInputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisKendaraanInputButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jenisKendaraanInputPanelLayout = new javax.swing.GroupLayout(jenisKendaraanInputPanel);
        jenisKendaraanInputPanel.setLayout(jenisKendaraanInputPanelLayout);
        jenisKendaraanInputPanelLayout.setHorizontalGroup(
            jenisKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisKendaraanInputPanelLayout.createSequentialGroup()
                        .addComponent(jenisKendaraanInputButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jenisKendaraanInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jenisKendaraanInputPanelLayout.setVerticalGroup(
            jenisKendaraanInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisKendaraanInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jenisKendaraanInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jenisKendaraanInputButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout kendaraanFormPanelLayout = new javax.swing.GroupLayout(kendaraanFormPanel);
        kendaraanFormPanel.setLayout(kendaraanFormPanelLayout);
        kendaraanFormPanelLayout.setHorizontalGroup(
            kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                        .addComponent(kendaraanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 308, Short.MAX_VALUE))
                    .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                        .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namaKendaraanInputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jenisKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hargaKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        kendaraanFormPanelLayout.setVerticalGroup(
            kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kendaraanFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kendaraanButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kendaraanFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jenisKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        specialAtributeInputPanel.setBackground(new java.awt.Color(255, 255, 255));

        specialAtributeInputLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputLabel.setForeground(new java.awt.Color(0, 0, 0));
        specialAtributeInputLabel.setText("Jenis Mesin");

        specialAtributeInputTextfield.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        specialAtributeInputTextfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                specialAtributeInputTextfieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout specialAtributeInputPanelLayout = new javax.swing.GroupLayout(specialAtributeInputPanel);
        specialAtributeInputPanel.setLayout(specialAtributeInputPanelLayout);
        specialAtributeInputPanelLayout.setHorizontalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(specialAtributeInputTextfield)
                    .addComponent(specialAtributeInputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        specialAtributeInputPanelLayout.setVerticalGroup(
            specialAtributeInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialAtributeInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(specialAtributeInputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialAtributeInputTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        motorScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        motorScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        motorTextArea.setColumns(20);
        motorTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        motorTextArea.setRows(5);
        motorScrollPane.setViewportView(motorTextArea);

        mobilScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        mobilTextArea.setColumns(20);
        mobilTextArea.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        mobilTextArea.setRows(5);
        mobilTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mobilScrollPane.setViewportView(mobilTextArea);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchKendaraanInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(mobilScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(motorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(kendaraanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchKendaraanInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(kendaraanFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(specialAtributeInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addComponent(simpanKendaraanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mobilScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addComponent(motorScrollPane))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchKendaraanInputTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKendaraanInputTextFieldKeyPressed
        
    }//GEN-LAST:event_searchKendaraanInputTextFieldKeyPressed

    private void searchKendaraanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKendaraanInputButtonActionPerformed
        doSearchKendaraan();
    }//GEN-LAST:event_searchKendaraanInputButtonActionPerformed

    private void barukanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barukanKendaraanButtonActionPerformed
        actionKendaraan = "update";
        setComponentsKendaraan(true);
        idKendaraanInputTextField.setEnabled(false);
    }//GEN-LAST:event_barukanKendaraanButtonActionPerformed

    private void hapusKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusKendaraanButtonActionPerformed
        int opsi = JOptionPane.showConfirmDialog(rootPane, "Yakin Ingin Hapus ?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if( opsi == JOptionPane.NO_OPTION || opsi == JOptionPane.CLOSED_OPTION)
            return;
        
        kc.deleteDataKendaraan(idKendaraanInputTextField.getText());
        clearText();
        setKendaraanEditDeleteButton(false);
        setComponentsKendaraan(false);
        showKendaraan();
    }//GEN-LAST:event_hapusKendaraanButtonActionPerformed

    private void tambahKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahKendaraanButtonActionPerformed
        actionKendaraan = "add";
        clearText();
        setKendaraanEditDeleteButton(false);
        setComponentsKendaraan(true);
        setKendaraanEditDeleteButton(false);
        
        idKendaraanInputTextField.setEnabled(false);
        idKendaraanInputTextField.setText(kc.generateId());
        jenisKendaraanInputButton.setText("Mobil");
        setSpecialAtributeLabel();
    }//GEN-LAST:event_tambahKendaraanButtonActionPerformed

    private void idKendaraanInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idKendaraanInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idKendaraanInputTextFieldActionPerformed

    private void hargaKendaraanInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hargaKendaraanInputTextfieldKeyTyped

    }//GEN-LAST:event_hargaKendaraanInputTextfieldKeyTyped

    private void jenisKendaraanInputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisKendaraanInputButtonActionPerformed
        switch(jenisKendaraanInputButton.getText()){
            case "Mobil": jenisKendaraanInputButton.setText("Motor"); break;
            case "Motor": jenisKendaraanInputButton.setText("Mobil"); break;
        }
        setSpecialAtributeLabel();
    }//GEN-LAST:event_jenisKendaraanInputButtonActionPerformed

    private void simpanKendaraanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKendaraanButtonActionPerformed
        if(actionKendaraan == null)
            return;
        try{
            inputKosongKendaraanException();
            InputSpecialAtributeKendaraanException();
            
            if(JOptionPane.showConfirmDialog(rootPane, "yakin ingin melakukan " + actionKendaraan + "?") == JOptionPane.CLOSED_OPTION)
                return;

            switch (actionKendaraan){
                case "add":
                    if(mobilIsSelected()){
                        mbl = new Mobil(specialAtributeInputTextfield.getText(), namaKendaraanInputTextField.getText(), 
                                jenisKendaraanInputButton.getText(), Float.parseFloat(hargaKendaraanInputTextfield.getText()));
                        mblc.insertDataKendaraan(mbl);
                    }else{
                        mtr = new Motor(Integer.parseInt(specialAtributeInputTextfield.getText()), namaKendaraanInputTextField.getText(), 
                                jenisKendaraanInputButton.getText(), Float.parseFloat(hargaKendaraanInputTextfield.getText()));
                        mtrc.insertDataKendaraan(mtr);
                    }
                    clearText();
                    setKendaraanEditDeleteButton(false);
                    setComponentsKendaraan(false);
                    showKendaraan();
                    break;
                case "update":
                    if(mobilIsSelected()){
                        mbl = new Mobil(specialAtributeInputTextfield.getText(),idKendaraanInputTextField.getText(), namaKendaraanInputTextField.getText(), 
                                jenisKendaraanInputButton.getText(), Float.parseFloat(hargaKendaraanInputTextfield.getText()));
                        mblc.updateDataKendaraan(mbl);
                    }else{
                        mtr = new Motor(Integer.parseInt(specialAtributeInputTextfield.getText()),idKendaraanInputTextField.getText(), namaKendaraanInputTextField.getText(), 
                                jenisKendaraanInputButton.getText(), Float.parseFloat(hargaKendaraanInputTextfield.getText()));
                        mtrc.updateDataKendaraan(mtr);
                    }
                    clearText();
                    setKendaraanEditDeleteButton(false);
                    setComponentsKendaraan(false);
                    showKendaraan();
                    break;
                default:
                    break;
            }
            actionKendaraan = null;
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(rootPane, e.message());
        }catch(InputSpecialAtributeException e){
            JOptionPane.showMessageDialog(rootPane, e.message(jenisKendaraanInputButton.getText()));
        }
    }//GEN-LAST:event_simpanKendaraanButtonActionPerformed

    private void specialAtributeInputTextfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_specialAtributeInputTextfieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_specialAtributeInputTextfieldKeyTyped

    private void searchKendaraanInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKendaraanInputTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchKendaraanInputTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barukanKendaraanButton;
    private javax.swing.JButton hapusKendaraanButton;
    private javax.swing.JLabel hargaKendaraanInputLabel;
    private javax.swing.JPanel hargaKendaraanInputPanel;
    private javax.swing.JTextField hargaKendaraanInputTextfield;
    private javax.swing.JLabel idKendaraanInputLabel;
    private javax.swing.JPanel idKendaraanInputPanel;
    private javax.swing.JTextField idKendaraanInputTextField;
    private javax.swing.JButton jenisKendaraanInputButton;
    private javax.swing.JLabel jenisKendaraanInputLabel;
    private javax.swing.JPanel jenisKendaraanInputPanel;
    private javax.swing.JPanel kendaraanButtonPanel;
    private javax.swing.JPanel kendaraanFormPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mobilScrollPane;
    private javax.swing.JTextArea mobilTextArea;
    private javax.swing.JScrollPane motorScrollPane;
    private javax.swing.JTextArea motorTextArea;
    private javax.swing.JLabel namaKendaraanInputLabel;
    private javax.swing.JPanel namaKendaraanInputPanel;
    private javax.swing.JTextField namaKendaraanInputTextField;
    private javax.swing.JButton searchKendaraanInputButton;
    private javax.swing.JLabel searchKendaraanInputLabel;
    private javax.swing.JPanel searchKendaraanInputPanel;
    private javax.swing.JTextField searchKendaraanInputTextField;
    private javax.swing.JButton simpanKendaraanButton;
    private javax.swing.JLabel specialAtributeInputLabel;
    private javax.swing.JPanel specialAtributeInputPanel;
    private javax.swing.JTextField specialAtributeInputTextfield;
    private javax.swing.JButton tambahKendaraanButton;
    // End of variables declaration//GEN-END:variables
}
